# Generated by Django 2.0.6 on 2018-06-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='bedtype',
            field=models.CharField(choices=[('1king', '1 King Bed'), ('2double', '2 Double Beds')], default='1king', max_length=50),
            preserve_default=False,
        ),
    ]
