# Generated by Django 2.0.6 on 2018-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20180618_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommapping',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
