# Generated by Django 2.0.6 on 2018-06-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_roommapping_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
