# Generated by Django 2.0.6 on 2018-06-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20180618_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='canada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='kid_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='kid_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='kid_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='kid_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='kids',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
