# Generated by Django 2.0.6 on 2018-06-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20180625_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='kids_ages',
        ),
    ]
